import { useState } from 'react'
import { motion } from 'framer-motion'
import Header from './Header'
import AIDietPlanner from './AIDietPlanner'
import AIWorkoutPlanner from './AIWorkoutPlanner'
import { SAMPLE_DATA, ANIMATIONS } from '@/constants'

export default function PlannerPage({ activePage }) {
	const [userData] = useState(SAMPLE_DATA)
	
	return (
		<div className="min-h-screen bg-cosmic">
			<Header activePage="/planner" />
			
			<main className="container mx-auto px-4 py-6">
				<motion.div
					className="mb-6"
					initial={{ opacity: 0, y: -20 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 0.5 }}
				>
					<h1 className="text-3xl font-bold text-dark">AI Fitness Planners</h1>
					<p className="text-gray-600 mt-2">
						Get personalized diet and workout plans generated by AI
					</p>
				</motion.div>
				
				<motion.div 
					className="grid grid-cols-1 lg:grid-cols-2 gap-6"
					initial="hidden"
					animate="visible"
					variants={ANIMATIONS.staggerChildren}
				>
					<motion.div variants={ANIMATIONS.slideIn}>
						<AIDietPlanner userData={userData} />
					</motion.div>
					
					<motion.div variants={ANIMATIONS.slideIn}>
						<AIWorkoutPlanner userData={userData} />
					</motion.div>
				</motion.div>
			</main>
			
			<motion.footer 
				className="mt-12 py-6 text-center text-gray-500 border-t border-gray-200"
				initial={{ opacity: 0, y: 20 }}
				animate={{ opacity: 1, y: 0 }}
				transition={{ delay: 1.2 }}
			>
				<p>Project by Jeevith</p>
			</motion.footer>
		</div>
	)
}